CREATE DATABASE ClinicaEj4;
CREATE TABLE TIPOESTUDIO(id INT PRIMARY KEY IDENTITY(1,1)NOT NULL,Descripcion VARCHAR(50),FechaBaja DateTime)
CREATE TABLE TIPOEMPLEADO(id INT PRIMARY KEY IDENTITY(1,1)NOT NULL,Descripcion VARCHAR(50),FechaBaja DateTime)
CREATE TABLE PACIENTE(id INT PRIMARY KEY IDENTITY(1,1)NOT NULL,Nombre VARCHAR(150),Apellido VARCHAR(150),Dni VARCHAR(50),Direccion VARCHAR(250))
CREATE TABLE EMPLEADO(id INT PRIMARY KEY IDENTITY(1,1)NOT NULL,TipoEmpleadoId  INT NOT NULL ,FOREIGN KEY (TipoEmpleadoId)REFERENCES TIPOEMPLEADO(TipoEmpleadoId),EmpleadoId INT NOT NULL,FOREIGN KEY(EmpleadoId)REFERENCES EMPLEADO(EmpleadoId),Fecha DATETIME,Informe varchar(250))