CREATE DATABASE InformaticaCarlos;
CREATE TABLE PRODUCTOS(id INT PRIMARY KEY IDENTITY(1,1)NOT NULL,Nombre VARCHAR(50),Descripcion VARCHAR(100),Precio numeric(18,2),ID_Categorias INT,FOREIGN KEY(id_Categorias) REFERENCES CATEGORIAS(id_Categorias))
CREATE TABLE CATEGORIAS(id_Categorias INT PRIMARY KEY IDENTITY(1,1)NOT NULL,NombreCategoria VARCHAR(70))
CREATE TABLE CLIENTE(id INT PRIMARY KEY IDENTITY (1,1)NOT NULL,Nombre VARCHAR(50),Apellido VARCHAR(50),DNI VARCHAR(50),Telefono VARCHAR(50),Direccion VARCHAR(100))
CREATE TABLE PROVEEDOR(id_Proveedor INT PRIMARY KEY IDENTITY(1,1)NOT NULL,Nombre VARCHAR(50),Producto_ID INT,FOREIGN KEY(Producto_ID)REFERENCES PRODUCTOS(id))
CREATE TABLE VENTAS(id INT PRIMARY KEY IDENTITY(1,1)NOT NULL,Detalle VARCHAR(70),Fecha DATETIME,ID_Cliente int,FOREIGN KEY (ID_Cliente) REFERENCES CLIENTES(id))